version = 1

[image]
apt_packages = [
  "libgl-dev",
  "libglu1-mesa-dev",
  "libltdl-dev",
  "libclang-dev",
  "libxcursor-dev",
  "libxi-dev",
  "libxinerama-dev",
  "libxmu-dev",
  "xorg-dev",
]

[workspace]
submodules = "recursive"
